# 1

In [264]:
import pandas as pd

def ld():
    # return pd.read_csv(r'c:\Users\admin\Documents\GitHub\syntetyczne26\processed_csv_serie_ph1_lmt_Giou_nopl_3met\merged_summary.csv', sep=',')
    return pd.read_csv(r'c:\Users\admin\Documents\GitHub\syntetyczne26\processed_csv_serie_ph1_nopl_3met\merged_summary.csv', sep=',')
            # .loc[:, ['faza1', 'src', 'tr_val', 'ph_nr', 'trg_var', 'stat_mean', 'stat_max']]

In [265]:
df0 = ld()
df0 = df0.drop(df0[df0.stat_count == 0].index)
df0.head()

,source_file,group_key,target_variable,stat_count,stat_mean,stat_std,stat_min,stat_25%,stat_50%,stat_75%,stat_max,top_correlated_variable,top_correlation_value
0,ph2_sub_gda,all,2_test/GDA/iou,162.0,0.729498,0.010548,0.699035,0.724360,0.730994,0.736842,0.748329,2_test/SYNT/iou,0.530376
1,ph2_sub_gda,all,2_test/SYNT/iou,162.0,0.781635,0.040708,0.648021,0.757877,0.788459,0.811951,0.843198,2_test/GDA/iou,0.530376
2,ph2_sub_gda,all,2_test/DK/iou,162.0,0.790780,0.022525,0.676919,0.783580,0.795325,0.805138,0.818687,epochs,0.562762
3,ph2_sub_gda,val=gda,2_test/GDA/iou,56.0,0.728201,0.010897,0.699035,0.724071,0.730441,0.735754,0.746150,2_test/SYNT/iou,0.463232
4,ph2_sub_gda,val=gda,2_test/SYNT/iou,56.0,0.779221,0.038148,0.648021,0.753640,0.787312,0.807357,0.837287,epochs,0.487846

In [266]:
df0 = df0[df0['group_key'].str.contains('val', na=False)]
# df0 = df0[df0['group_key'].str.contains('val', na=False)]
df0 = df0[~df0['group_key'].str.contains('Sweep', na=False)]
df0.head()

,source_file,group_key,target_variable,stat_count,stat_mean,stat_std,stat_min,stat_25%,stat_50%,stat_75%,stat_max,top_correlated_variable,top_correlation_value
3,ph2_sub_gda,val=gda,2_test/GDA/iou,56.0,0.728201,0.010897,0.699035,0.724071,0.730441,0.735754,0.746150,2_test/SYNT/iou,0.463232
4,ph2_sub_gda,val=gda,2_test/SYNT/iou,56.0,0.779221,0.038148,0.648021,0.753640,0.787312,0.807357,0.837287,epochs,0.487846
5,ph2_sub_gda,val=gda,2_test/DK/iou,56.0,0.791051,0.020702,0.715499,0.784030,0.796929,0.805558,0.818687,epochs,0.597013
6,ph2_sub_gda,val=m,2_test/GDA/iou,56.0,0.727870,0.011585,0.705030,0.717292,0.730895,0.737432,0.747984,2_test/SYNT/iou,0.633742
7,ph2_sub_gda,val=m,2_test/SYNT/iou,56.0,0.772069,0.046682,0.648406,0.750063,0.780863,0.805164,0.843198,2_test/GDA/iou,0.633742

In [267]:
# 'faza1', 'src', 'tr_val', 'ph_nr', 'trg_var',
df0['faza1'] = df0['source_file'].astype(str).str.split('_').str[0]
df0['src'] = 'x'
df0.loc[df0['source_file'].astype(str).str.split('_').str.len() > 2, 'src'] = df0['source_file'].astype(str).str.split('_').str[1] + '_' + df0['source_file'].astype(str).str.split('_').str[2]
df0['tr_val'] = 's' # start with tr
df0.loc[df0['faza1'] == 'ph2', 'tr_val'] = 'subm'
df0.loc[df0['faza1'] == 'ph3', 'tr_val'] = 'dk'
df0.loc[df0['faza1'] == 'dk', 'tr_val'] = 'dk'
df0.loc[df0['faza1'] == 'subs', 'tr_val'] = 'sub'
df0.loc[df0['faza1'].str.contains('S', na=False), 'tr_val'] = 'sub'
df0.loc[df0['faza1'].str.contains('subs', na=False), 'tr_val'] = 'sub'
# df0.loc[df0['src'].str.contains('m', na=False), 'tr_val'] = 'm' # nie
df0['tr_val'] = df0['tr_val'] + '_' + df0['group_key'].astype(str).str.split('=').str[1] # join with val
df0['ph_nr'] = df0['target_variable'].astype(str).str[0]
df0['trg_var'] = 'DK'
df0.loc[df0['target_variable'].str.contains('SYNT', na=False), 'trg_var'] = 'SYNT'
df0.loc[df0['target_variable'].str.contains('GDA', na=False), 'trg_var'] = 'GDA'
df0.head()

,source_file,group_key,target_variable,stat_count,stat_mean,stat_std,stat_min,stat_25%,stat_50%,stat_75%,stat_max,top_correlated_variable,top_correlation_value,faza1,src,tr_val,ph_nr,trg_var
3,ph2_sub_gda,val=gda,2_test/GDA/iou,56.0,0.728201,0.010897,0.699035,0.724071,0.730441,0.735754,0.746150,2_test/SYNT/iou,0.463232,ph2,sub_gda,subm_gda,2,GDA
4,ph2_sub_gda,val=gda,2_test/SYNT/iou,56.0,0.779221,0.038148,0.648021,0.753640,0.787312,0.807357,0.837287,epochs,0.487846,ph2,sub_gda,subm_gda,2,SYNT
5,ph2_sub_gda,val=gda,2_test/DK/iou,56.0,0.791051,0.020702,0.715499,0.784030,0.796929,0.805558,0.818687,epochs,0.597013,ph2,sub_gda,subm_gda,2,DK
6,ph2_sub_gda,val=m,2_test/GDA/iou,56.0,0.727870,0.011585,0.705030,0.717292,0.730895,0.737432,0.747984,2_test/SYNT/iou,0.633742,ph2,sub_gda,subm_m,2,GDA
7,ph2_sub_gda,val=m,2_test/SYNT/iou,56.0,0.772069,0.046682,0.648406,0.750063,0.780863,0.805164,0.843198,2_test/GDA/iou,0.633742,ph2,sub_gda,subm_m,2,SYNT

-----------------

# 2

In [268]:
# import pandas as pd

# def ld():
#     return pd.read_csv(r'c:\Users\admin\Documents\GitHub\syntetyczne26\rozwiklane.csv', sep=',')\
#             .rename(columns={'faza2': 'src'})\
#             .loc[:, ['faza1', 'src', 'tr_val', 'ph_nr', 'trg_var', 'stat_mean', 'stat_max']]
    
def ld():
    return df0.loc[:, ['faza1', 'src', 'tr_val', 'ph_nr', 'trg_var', 'stat_mean', 'stat_max']]

def df_ph(df, ph):
    return df[df['ph_nr'] == ph]

In [269]:
df1 = df_ph(ld(), '1')
# df1 = df_ph(ld(), 1)
df1.head()

    faza1 src  tr_val ph_nr trg_var  stat_mean  stat_max
123    dk   x   dk_dk     1     GDA   0.692065  0.752679
124    dk   x   dk_dk     1    SYNT   0.438859  0.586819
125    dk   x   dk_dk     1      DK   0.775123  0.819903
126    dk   x  dk_gda     1     GDA   0.732748  0.764761
127    dk   x  dk_gda     1    SYNT   0.488591  0.560278

In [270]:
df2 = df_ph(ld(), '2')
# df2 = df_ph(ld(), 2)
# df2 = df2[df2['src'] != 'dk_dk'] # SYNT
# df2 = df2[~df2['src'].str.contains('gda', na=True)] # SYNT
# df2 = df2[~df2['src'].str.contains('s', na=True)] # GDADK
df2.head()

  faza1      src    tr_val ph_nr trg_var  stat_mean  stat_max
3   ph2  sub_gda  subm_gda     2     GDA   0.728201  0.746150
4   ph2  sub_gda  subm_gda     2    SYNT   0.779221  0.837287
5   ph2  sub_gda  subm_gda     2      DK   0.791051  0.818687
6   ph2  sub_gda    subm_m     2     GDA   0.727870  0.747984
7   ph2  sub_gda    subm_m     2    SYNT   0.772069  0.843198

In [271]:
df3 = df_ph(ld(), '3')
# df3 = df_ph(ld(), 3)
df3.head()

    faza1       src  tr_val ph_nr trg_var  stat_mean  stat_max
399   ph3  subm_gda   dk_dk     3     GDA   0.745487  0.754875
402   ph3  subm_gda   dk_dk     3    SYNT   0.798757  0.836882
404   ph3  subm_gda   dk_dk     3      DK   0.808501  0.820677
405   ph3  subm_gda  dk_gda     3     GDA   0.745290  0.757549
408   ph3  subm_gda  dk_gda     3    SYNT   0.795818  0.836495

In [272]:
df12 = pd.merge(df1, df2, how='inner', left_on=['tr_val', 'trg_var'], right_on=['src', 'trg_var'])
# df12 = pd.merge(df2, df1, how='left', right_on=['tr_val', 'trg_var'], left_on=['src', 'trg_var'])
df12.head()

,faza1_x,src_x,tr_val_x,ph_nr_x,trg_var,stat_mean_x,stat_max_x,faza1_y,src_y,tr_val_y,ph_nr_y,stat_mean_y,stat_max_y
0,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_gda,2,0.728030,0.759344
1,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_m,2,0.728209,0.753719
2,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_s,2,0.727449,0.757477
3,dk,x,dk_dk,1,SYNT,0.438859,0.586819,ph2,dk_dk,subm_gda,2,0.691366,0.833610
4,dk,x,dk_dk,1,SYNT,0.438859,0.586819,ph2,dk_dk,subm_m,2,0.713015,0.835740

In [273]:
df123 = pd.merge(df12, df3, how='inner', left_on=['tr_val_y', 'trg_var'], right_on=['src', 'trg_var'])
df123.head()

,faza1_x,src_x,tr_val_x,ph_nr_x,trg_var,stat_mean_x,stat_max_x,faza1_y,src_y,tr_val_y,ph_nr_y,stat_mean_y,stat_max_y,faza1,src,tr_val,ph_nr,stat_mean,stat_max
0,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_gda,2,0.728030,0.759344,ph3,subm_gda,dk_dk,3,0.745487,0.754875
1,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_gda,2,0.728030,0.759344,ph3,subm_gda,dk_gda,3,0.745290,0.757549
2,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_m,2,0.728209,0.753719,ph3,subm_m,dk_dk,3,0.746703,0.751661
3,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_m,2,0.728209,0.753719,ph3,subm_m,dk_gda,3,0.745797,0.751909
4,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_s,2,0.727449,0.757477,ph3,subm_s,dk_dk,3,0.744475,0.753790

In [274]:
# df123.to_csv('df123v2.csv')

In [275]:
df = df123
# df['comb_key'] = str(df['ph_nr_x']) + '_' + df['src_x'] + '_' + df['tr_val_x'] + \
#                 str(df['ph_nr_y']) + '_' + df['src_y'] + '_' + df['tr_val_y'] + \
#                 str(df['ph_nr']) + '_' + df['src'] + '_' + df['tr_val']

df['comb_key'] = df['src_x'] + '_' + df['tr_val_x'] + '|' + \
                df['src_y'] + '_' + df['tr_val_y'] + '|' + \
                df['src'] + '_' + df['tr_val'] + '_' + df['trg_var']
df.head()

,faza1_x,src_x,tr_val_x,ph_nr_x,trg_var,stat_mean_x,stat_max_x,faza1_y,src_y,tr_val_y,ph_nr_y,stat_mean_y,stat_max_y,faza1,src,tr_val,ph_nr,stat_mean,stat_max,comb_key
0,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_gda,2,0.728030,0.759344,ph3,subm_gda,dk_dk,3,0.745487,0.754875,x_dk_dk|dk_dk_subm_gda|subm_gda_dk_dk_GDA
1,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_gda,2,0.728030,0.759344,ph3,subm_gda,dk_gda,3,0.745290,0.757549,x_dk_dk|dk_dk_subm_gda|subm_gda_dk_gda_GDA
2,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_m,2,0.728209,0.753719,ph3,subm_m,dk_dk,3,0.746703,0.751661,x_dk_dk|dk_dk_subm_m|subm_m_dk_dk_GDA
3,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_m,2,0.728209,0.753719,ph3,subm_m,dk_gda,3,0.745797,0.751909,x_dk_dk|dk_dk_subm_m|subm_m_dk_gda_GDA
4,dk,x,dk_dk,1,GDA,0.692065,0.752679,ph2,dk_dk,subm_s,2,0.727449,0.757477,ph3,subm_s,dk_dk,3,0.744475,0.753790,x_dk_dk|dk_dk_subm_s|subm_s_dk_dk_GDA

In [276]:
# df.to_csv('dff.csv')

In [277]:
# df.melt(['comb_key']).head()

In [278]:
# pd.wide_to_long(df, ['stat'], 'comb_key', '', "_", '')

In [279]:
# import pandas as pd

# def clean_data(df):
#     # Filtruj wiersze na podstawie kolumnie: 'faza1'
#     df = df[df['faza1'].str.contains("ph", regex=False, na=False, case=False)]
#     # Filtruj wiersze na podstawie kolumnie: 'faza2'
#     df = df[df['faza2'].str.contains("gda", regex=False, na=False, case=False)]
#     # Wybierz kolumny: 'faza1', 'faza2' i inne kolumny (5)
#     df = df.loc[:, ['faza1', 'faza2', 'tr_val', 'ph_nr', 'trg_var', 'stat_mean', 'stat_max']]
#     df = pd.merge(df, df, how="inner", left_on="faza2", right_on="tr_val")
#     return df

# # Załadowana zmienna „df” z identyfikatora URI: c:\Users\admin\Documents\GitHub\syntetyczne26\rozwiklane.csv
# df = pd.read_csv(r'c:\Users\admin\Documents\GitHub\syntetyczne26\rozwiklane.csv', sep=',')

# df_clean = clean_data(df.copy())
# df_clean.head()

In [280]:
# df = pd.read_csv(r'c:\Users\admin\Documents\GitHub\syntetyczne26\rozwiklane.csv', sep=',')
# df = df[df['faza1'].str.contains("ph", regex=False, na=False, case=False)]
# df = df[df['faza2'].str.contains("gda", regex=False, na=False, case=False)]
# df = df.loc[:, ['faza1', 'faza2', 'tr_val', 'ph_nr', 'trg_var', 'stat_mean', 'stat_max']]

# df = pd.merge(df_clean, df, how="inner", left_on="faza2_y", right_on="tr_val")
# df.head()

# 3

In [281]:
df_x = df[['comb_key', 'trg_var', 'ph_nr_x', 'stat_mean_x']].copy()
df_x.columns = ['comb_key', 'trg_var', 'ph_nr', 'stat_mean']

df_y = df[['comb_key', 'trg_var', 'ph_nr_y', 'stat_mean_y']].copy()
df_y.columns = ['comb_key', 'trg_var', 'ph_nr', 'stat_mean']

df_blank = df[['comb_key', 'trg_var', 'ph_nr', 'stat_mean']].copy()

# Combine (stack) them all together into one long format dataframe
df_long = pd.concat([df_x, df_y, df_blank], ignore_index=True)

# 3. Clean the comb_key to create the "series"
# .str.rsplit('_', n=1).str[0] splits the string at the very last underscore and removes it (e.g., dropping _DK)
df_long['series'] = df_long['comb_key'].str.rsplit('_', n=1).str[0]
# df_long['series'] = df_long['comb_key'].str.replace('x_', '').str


# df_long.to_csv('df_long_total.csv')

In [282]:
df_long.head()

,comb_key,trg_var,ph_nr,stat_mean,series
0,x_dk_dk|dk_dk_subm_gda|subm_gda_dk_dk_GDA,GDA,1,0.692065,x_dk_dk|dk_dk_subm_gda|subm_gda_dk_dk
1,x_dk_dk|dk_dk_subm_gda|subm_gda_dk_gda_GDA,GDA,1,0.692065,x_dk_dk|dk_dk_subm_gda|subm_gda_dk_gda
2,x_dk_dk|dk_dk_subm_m|subm_m_dk_dk_GDA,GDA,1,0.692065,x_dk_dk|dk_dk_subm_m|subm_m_dk_dk
3,x_dk_dk|dk_dk_subm_m|subm_m_dk_gda_GDA,GDA,1,0.692065,x_dk_dk|dk_dk_subm_m|subm_m_dk_gda
4,x_dk_dk|dk_dk_subm_s|subm_s_dk_dk_GDA,GDA,1,0.692065,x_dk_dk|dk_dk_subm_s|subm_s_dk_dk

In [283]:
# df_long.to_csv('df_long_all_SYNT.csv')
# df_long.to_csv('df_long_all_GDADK.csv')
df_long.to_csv('df_long_all_total.csv')
# df_long.to_csv('df_long_SYNT.csv')
# df_long.to_csv('df_long_GDADK.csv')
# df_long.to_csv('df_long_total.csv')