# 1

In [116]:
import pandas as pd

def ld():
    return pd.read_csv(r'c:\Users\admin\Documents\GitHub\syntetyczne26\processed_csv_serie_ph1_lmt_Giou_nopl_3met\merged_summary.csv', sep=',')
            # .loc[:, ['faza1', 'src', 'tr_val', 'ph_nr', 'trg_var', 'stat_mean', 'stat_max']]

In [117]:
df0 = ld()
df0 = df0.drop(df0[df0.stat_count == 0].index)
df0.head()

,source_file,group_key,target_variable,stat_count,stat_mean,stat_std,stat_min,stat_25%,stat_50%,stat_75%,stat_max,top_correlated_variable,top_correlation_value
0,30,all,1_test/GDA/iou,17.0,0.666214,0.022486,0.631215,0.645544,0.674564,0.682502,0.702594,1_test/DK/iou,0.888700
1,30,all,1_test/SYNT/iou,17.0,0.818374,0.020740,0.799183,0.802679,0.807199,0.838198,0.861660,1_test/DK/iou,-0.956654
2,30,all,1_test/DK/iou,17.0,0.540567,0.052200,0.436574,0.486732,0.557884,0.580081,0.601329,1_test/SYNT/iou,-0.956654
3,30,val=gda,1_test/GDA/iou,16.0,0.667506,0.022562,0.631215,0.648296,0.675412,0.682763,0.702594,1_test/DK/iou,0.881668
4,30,val=gda,1_test/SYNT/iou,16.0,0.816997,0.020603,0.799183,0.802660,0.806128,0.837434,0.861660,1_test/DK/iou,-0.953142

In [118]:
df0 = df0[df0['group_key'].str.contains('val', na=False)]
df0 = df0[df0['group_key'].str.contains('val', na=False)]
df0 = df0[~df0['group_key'].str.contains('Sweep', na=False)]
df0.head()

,source_file,group_key,target_variable,stat_count,stat_mean,stat_std,stat_min,stat_25%,stat_50%,stat_75%,stat_max,top_correlated_variable,top_correlation_value
3,30,val=gda,1_test/GDA/iou,16.0,0.667506,0.022562,0.631215,0.648296,0.675412,0.682763,0.702594,1_test/DK/iou,0.881668
4,30,val=gda,1_test/SYNT/iou,16.0,0.816997,0.020603,0.799183,0.802660,0.806128,0.837434,0.861660,1_test/DK/iou,-0.953142
5,30,val=gda,1_test/DK/iou,16.0,0.544034,0.051851,0.436574,0.492584,0.562203,0.581963,0.601329,1_test/SYNT/iou,-0.953142
6,30,val=s,1_test/GDA/iou,1.0,0.645544,NaN,0.645544,0.645544,0.645544,0.645544,0.645544,NaN,NaN
7,30,val=s,1_test/SYNT/iou,1.0,0.840398,NaN,0.840398,0.840398,0.840398,0.840398,0.840398,NaN,NaN

In [172]:
# 'faza1', 'src', 'tr_val', 'ph_nr', 'trg_var',
df0['faza1'] = df0['source_file'].astype(str).str.split('_').str[0]
# df0['src'] = df0['source_file'].astype(str).str.split('_').str[1] if len(df0['source_file'].astype(str).str.split('_')) > 1 else 'x'
df0['src'] = 'x'
# df0.loc[df0['source_file'].astype(str).str.split('_').str.len() > 1, 'src'] = df0['source_file'].astype(str).str.split('_').str[1]
df0.loc[df0['source_file'].astype(str).str.split('_').str.len() > 2, 'src'] = df0['source_file'].astype(str).str.split('_').str[1] + '_' + df0['source_file'].astype(str).str.split('_').str[2]
# df0.loc[df0['source_file'].astype(str).str.split('_').str.len() > 1, 'src'] = df0['source_file'].astype(str).str.split('_').str[1]
df0['tr_val'] = 's'
df0.loc[df0['faza1'] == 'ph2', 'tr_val'] = 'subm'
df0.loc[df0['faza1'] == 'ph3', 'tr_val'] = 'dk'
df0.loc[df0['src'].str.contains('m', na=False), 'tr_val'] = 'm'
df0['tr_val'] = df0['tr_val'] + '_' + df0['group_key'].astype(str).str.split('=').str[1]
df0['ph_nr'] = df0['target_variable'].astype(str).str[0]
df0['trg_var'] = 'DK'
df0.loc[df0['target_variable'].str.contains('SYNT', na=False), 'trg_var'] = 'SYNT'
df0.loc[df0['target_variable'].str.contains('GDA', na=False), 'trg_var'] = 'GDA'
df0.head()

,source_file,group_key,target_variable,stat_count,stat_mean,stat_std,stat_min,stat_25%,stat_50%,stat_75%,stat_max,top_correlated_variable,top_correlation_value,faza1,src,tr_val,ph_nr,trg_var
3,30,val=gda,1_test/GDA/iou,16.0,0.667506,0.022562,0.631215,0.648296,0.675412,0.682763,0.702594,1_test/DK/iou,0.881668,30,x,s_gda,1,GDA
4,30,val=gda,1_test/SYNT/iou,16.0,0.816997,0.020603,0.799183,0.802660,0.806128,0.837434,0.861660,1_test/DK/iou,-0.953142,30,x,s_gda,1,SYNT
5,30,val=gda,1_test/DK/iou,16.0,0.544034,0.051851,0.436574,0.492584,0.562203,0.581963,0.601329,1_test/SYNT/iou,-0.953142,30,x,s_gda,1,DK
6,30,val=s,1_test/GDA/iou,1.0,0.645544,NaN,0.645544,0.645544,0.645544,0.645544,0.645544,NaN,NaN,30,x,s_s,1,GDA
7,30,val=s,1_test/SYNT/iou,1.0,0.840398,NaN,0.840398,0.840398,0.840398,0.840398,0.840398,NaN,NaN,30,x,s_s,1,SYNT

-----------------

# 2

In [173]:
# import pandas as pd

# def ld():
#     return pd.read_csv(r'c:\Users\admin\Documents\GitHub\syntetyczne26\rozwiklane.csv', sep=',')\
#             .rename(columns={'faza2': 'src'})\
#             .loc[:, ['faza1', 'src', 'tr_val', 'ph_nr', 'trg_var', 'stat_mean', 'stat_max']]
    
def ld():
    return df0.loc[:, ['faza1', 'src', 'tr_val', 'ph_nr', 'trg_var', 'stat_mean', 'stat_max']]

def df_ph(df, ph):
    return df[df['ph_nr'] == ph]

In [174]:
df1 = df_ph(ld(), '1')
# df1 = df_ph(ld(), 1)
df1.head()

  faza1 src tr_val ph_nr trg_var  stat_mean  stat_max
3    30   x  s_gda     1     GDA   0.667506  0.702594
4    30   x  s_gda     1    SYNT   0.816997  0.861660
5    30   x  s_gda     1      DK   0.544034  0.601329
6    30   x    s_s     1     GDA   0.645544  0.645544
7    30   x    s_s     1    SYNT   0.840398  0.840398

In [175]:
df2 = df_ph(ld(), '2')
# df2 = df_ph(ld(), 2)
df2.head()

   faza1     src    tr_val ph_nr trg_var  stat_mean  stat_max
48   ph2  dk_gda  subm_gda     2     GDA   0.740525  0.777972
49   ph2  dk_gda  subm_gda     2    SYNT   0.691096  0.811168
50   ph2  dk_gda  subm_gda     2      DK   0.800843  0.819017
51   ph2  dk_gda    subm_m     2     GDA   0.743113  0.776937
52   ph2  dk_gda    subm_m     2    SYNT   0.725759  0.828063

In [176]:
df3 = df_ph(ld(), '3')
# df3 = df_ph(ld(), 3)
df3.head()

    faza1     src tr_val ph_nr trg_var  stat_mean  stat_max
285   ph3  subm_m   m_dk     3     GDA   0.746703  0.751661
288   ph3  subm_m   m_dk     3    SYNT   0.810725  0.838262
290   ph3  subm_m   m_dk     3      DK   0.804916  0.821736
291   ph3  subm_m  m_gda     3     GDA   0.745797  0.751909
294   ph3  subm_m  m_gda     3    SYNT   0.809516  0.837269

In [177]:
df12 = pd.merge(df1, df2, how='inner', left_on=['tr_val', 'trg_var'], right_on=['src', 'trg_var'])
# df12 = pd.merge(df2, df1, how='left', right_on=['tr_val', 'trg_var'], left_on=['src', 'trg_var'])
df12.head()

,faza1_x,src_x,tr_val_x,ph_nr_x,trg_var,stat_mean_x,stat_max_x,faza1_y,src_y,tr_val_y,ph_nr_y,stat_mean_y,stat_max_y
0,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_gda,2,0.731981,0.747124
1,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_m,2,0.728940,0.749387
2,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_s,2,0.728170,0.747182
3,30,x,s_gda,1,SYNT,0.816997,0.861660,ph2,s_gda,subm_gda,2,0.816268,0.856251
4,30,x,s_gda,1,SYNT,0.816997,0.861660,ph2,s_gda,subm_m,2,0.818769,0.854581

In [178]:
df123 = pd.merge(df12, df3, how='inner', left_on=['tr_val_y', 'trg_var'], right_on=['src', 'trg_var'])
df123.head()

,faza1_x,src_x,tr_val_x,ph_nr_x,trg_var,stat_mean_x,stat_max_x,faza1_y,src_y,tr_val_y,ph_nr_y,stat_mean_y,stat_max_y,faza1,src,tr_val,ph_nr,stat_mean,stat_max
0,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_m,2,0.728940,0.749387,ph3,subm_m,m_dk,3,0.746703,0.751661
1,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_m,2,0.728940,0.749387,ph3,subm_m,m_gda,3,0.745797,0.751909
2,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_s,2,0.728170,0.747182,ph3,subm_s,m_dk,3,0.744475,0.753790
3,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_s,2,0.728170,0.747182,ph3,subm_s,m_gda,3,0.743842,0.753114
4,30,x,s_gda,1,SYNT,0.816997,0.861660,ph2,s_gda,subm_m,2,0.818769,0.854581,ph3,subm_m,m_dk,3,0.810725,0.838262

In [179]:
# df123.to_csv('df123v2.csv')

In [180]:
df = df123
# df['comb_key'] = str(df['ph_nr_x']) + '_' + df['src_x'] + '_' + df['tr_val_x'] + \
#                 str(df['ph_nr_y']) + '_' + df['src_y'] + '_' + df['tr_val_y'] + \
#                 str(df['ph_nr']) + '_' + df['src'] + '_' + df['tr_val']

df['comb_key'] = df['src_x'] + '_' + df['tr_val_x'] + '|' + \
                df['src_y'] + '_' + df['tr_val_y'] + '|' + \
                df['src'] + '_' + df['tr_val'] + '_' + df['trg_var']
df.head()

,faza1_x,src_x,tr_val_x,ph_nr_x,trg_var,stat_mean_x,stat_max_x,faza1_y,src_y,tr_val_y,ph_nr_y,stat_mean_y,stat_max_y,faza1,src,tr_val,ph_nr,stat_mean,stat_max,comb_key
0,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_m,2,0.728940,0.749387,ph3,subm_m,m_dk,3,0.746703,0.751661,x_s_gda|s_gda_subm_m|subm_m_m_dk_GDA
1,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_m,2,0.728940,0.749387,ph3,subm_m,m_gda,3,0.745797,0.751909,x_s_gda|s_gda_subm_m|subm_m_m_gda_GDA
2,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_s,2,0.728170,0.747182,ph3,subm_s,m_dk,3,0.744475,0.753790,x_s_gda|s_gda_subm_s|subm_s_m_dk_GDA
3,30,x,s_gda,1,GDA,0.667506,0.702594,ph2,s_gda,subm_s,2,0.728170,0.747182,ph3,subm_s,m_gda,3,0.743842,0.753114,x_s_gda|s_gda_subm_s|subm_s_m_gda_GDA
4,30,x,s_gda,1,SYNT,0.816997,0.861660,ph2,s_gda,subm_m,2,0.818769,0.854581,ph3,subm_m,m_dk,3,0.810725,0.838262,x_s_gda|s_gda_subm_m|subm_m_m_dk_SYNT

In [181]:
# df.to_csv('dff.csv')

In [182]:
# df.melt(['comb_key']).head()

In [183]:
# pd.wide_to_long(df, ['stat'], 'comb_key', '', "_", '')

In [184]:
# import pandas as pd

# def clean_data(df):
#     # Filtruj wiersze na podstawie kolumnie: 'faza1'
#     df = df[df['faza1'].str.contains("ph", regex=False, na=False, case=False)]
#     # Filtruj wiersze na podstawie kolumnie: 'faza2'
#     df = df[df['faza2'].str.contains("gda", regex=False, na=False, case=False)]
#     # Wybierz kolumny: 'faza1', 'faza2' i inne kolumny (5)
#     df = df.loc[:, ['faza1', 'faza2', 'tr_val', 'ph_nr', 'trg_var', 'stat_mean', 'stat_max']]
#     df = pd.merge(df, df, how="inner", left_on="faza2", right_on="tr_val")
#     return df

# # Załadowana zmienna „df” z identyfikatora URI: c:\Users\admin\Documents\GitHub\syntetyczne26\rozwiklane.csv
# df = pd.read_csv(r'c:\Users\admin\Documents\GitHub\syntetyczne26\rozwiklane.csv', sep=',')

# df_clean = clean_data(df.copy())
# df_clean.head()

In [185]:
# df = pd.read_csv(r'c:\Users\admin\Documents\GitHub\syntetyczne26\rozwiklane.csv', sep=',')
# df = df[df['faza1'].str.contains("ph", regex=False, na=False, case=False)]
# df = df[df['faza2'].str.contains("gda", regex=False, na=False, case=False)]
# df = df.loc[:, ['faza1', 'faza2', 'tr_val', 'ph_nr', 'trg_var', 'stat_mean', 'stat_max']]

# df = pd.merge(df_clean, df, how="inner", left_on="faza2_y", right_on="tr_val")
# df.head()

# 3

In [ ]:
df_x = df[['comb_key', 'trg_var', 'ph_nr_x', 'stat_mean_x']].copy()
df_x.columns = ['comb_key', 'trg_var', 'ph_nr', 'stat_mean']

df_y = df[['comb_key', 'trg_var', 'ph_nr_y', 'stat_mean_y']].copy()
df_y.columns = ['comb_key', 'trg_var', 'ph_nr', 'stat_mean']

df_blank = df[['comb_key', 'trg_var', 'ph_nr', 'stat_mean']].copy()

# Combine (stack) them all together into one long format dataframe
df_long = pd.concat([df_x, df_y, df_blank], ignore_index=True)

# 3. Clean the comb_key to create the "series"
# .str.rsplit('_', n=1).str[0] splits the string at the very last underscore and removes it (e.g., dropping _DK)
df_long['series'] = df_long['comb_key'].str.rsplit('_', n=1).str[0]
# df_long['series'] = df_long['comb_key'].str.replace('x_', '').str


df_long.to_csv('df_long_total.csv')

In [187]:
df_long.head()

,comb_key,trg_var,ph_nr,stat_mean,series
0,x_s_gda|s_gda_subm_m|subm_m_m_dk_GDA,GDA,1,0.667506,x_s_gda|s_gda_subm_m|subm_m_m_dk
1,x_s_gda|s_gda_subm_m|subm_m_m_gda_GDA,GDA,1,0.667506,x_s_gda|s_gda_subm_m|subm_m_m_gda
2,x_s_gda|s_gda_subm_s|subm_s_m_dk_GDA,GDA,1,0.667506,x_s_gda|s_gda_subm_s|subm_s_m_dk
3,x_s_gda|s_gda_subm_s|subm_s_m_gda_GDA,GDA,1,0.667506,x_s_gda|s_gda_subm_s|subm_s_m_gda
4,x_s_gda|s_gda_subm_m|subm_m_m_dk_SYNT,SYNT,1,0.816997,x_s_gda|s_gda_subm_m|subm_m_m_dk